// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2p28xTEXysFkXUcHxA6cUjE3QtPsxq6A',
    appId: '1:349737232952:web:36416adaf0adc40851d4cd',
    messagingSenderId: '349737232952',
    projectId: 'itutor-6659e',
    authDomain: 'itutor-6659e.firebaseapp.com',
    storageBucket: 'itutor-6659e.appspot.com',
    measurementId: 'G-G0Q2MKM7HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr4Ch2xylxxCUoEYVnGFB4WKdaaXFmU0c',
    appId: '1:349737232952:android:bae883ed52fba36251d4cd',
    messagingSenderId: '349737232952',
    projectId: 'itutor-6659e',
    storageBucket: 'itutor-6659e.appspot.com',
  );
}
